/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-22 01:20:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class study_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"EUC-KR\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	var users = [\r\n");
      out.write("		 {id: 1, name: 'ID', age: 36}\r\n");
      out.write("		,{id: 2, name: 'BJ', age: 32}\r\n");
      out.write("		,{id: 3, name: 'JM', age: 32}\r\n");
      out.write("		,{id: 4, name: 'PJ', age: 27}\r\n");
      out.write("		,{id: 5, name: 'HA', age: 25}\r\n");
      out.write("		,{id: 6, name: 'JE', age: 26}\r\n");
      out.write("		,{id: 7, name: 'JI', age: 31}\r\n");
      out.write("		,{id: 8, name: 'MP', age: 23}\r\n");
      out.write("	];\r\n");
      out.write("	\r\n");
      out.write("/*	1. 명령형 코드 */\r\n");
      out.write("	//	1) 30세 이상인 users를 거른다. \r\n");
      out.write("	var temp_users  = [];\r\n");
      out.write("	for(var i=0;i<users.length;i++){\r\n");
      out.write("		if(users[i].age >= 30){\r\n");
      out.write("			temp_users.push(users[i]);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("//	console.log(temp_users);\r\n");
      out.write("	\r\n");
      out.write("	//	2) 30세 이상인 users의 names를 수집한다.\r\n");
      out.write("	var names = [];\r\n");
      out.write("	for(var i=0;i<temp_users.length;i++){\r\n");
      out.write("		names.push(temp_users[i].name);\r\n");
      out.write("	}\r\n");
      out.write("//	console.log(names);\r\n");
      out.write("	\r\n");
      out.write("	//	3)30세 미만인 users를 거른다.\r\n");
      out.write("	var temp_users  = [];\r\n");
      out.write("	for(var i=0;i<users.length;i++){\r\n");
      out.write("		if(users[i].age < 30){\r\n");
      out.write("			temp_users.push(users[i]);\r\n");
      out.write("		}\r\n");
      out.write("	}	\r\n");
      out.write("//	console.log(temp_users);\r\n");
      out.write("	\r\n");
      out.write("	//	4)30세 미만인 users의 ages를 수집한다.\r\n");
      out.write("	var ages = [];\r\n");
      out.write("	for(var i=0;i<temp_users.length;i++){\r\n");
      out.write("		ages.push(temp_users[i].age);\r\n");
      out.write("	}\r\n");
      out.write("//	console.log(ages);\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("/* 	2. _filter, _map으로 리팩토링 */\r\n");
      out.write("	function _filter(list, predi){\r\n");
      out.write("		var new_list = [];\r\n");
      out.write("		for(var i=0;i<list.length;i++){\r\n");
      out.write("			if(predi(list[i])){\r\n");
      out.write("				new_list.push(list[i]);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return new_list;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/*	    원래 있는 값을 직접 변경하지 않고 변형된 새로운 값을 리턴하는 방식으로 값을 변형해나가기 \r\n");
      out.write("	    필터와 같은 함수인 응용형 함수(응용형 프로그래밍, 적용형 프로그래밍)는 함수가 함수를 받아서 \r\n");
      out.write("	    원하는 시점에 해당하는 함수가 알고있는 인자를 적용하는 식으로 프로그래밍 하는 것 \r\n");
      out.write("	    필터함수를 고차함수라고도 함\r\n");
      out.write("	    고차함수는 함수를 인자로 받거나 함수를 리턴하거나 함수 안에서 인자로 받은 함수를 실행하는 함수	*/\r\n");
      out.write("	\r\n");
      out.write("//	console.log( _filter(users, function(user) { return user.age >= 30; }));\r\n");
      out.write("	\r\n");
      out.write("//	console.log( _filter(users, function(user) { return user.age < 30; }));	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("//	console.log( _filter([1, 2, 3, 4], function(num) { return num % 2; }));\r\n");
      out.write("	\r\n");
      out.write("//	console.log( _filter([1, 2, 3, 4], function(num) { return !(num % 2); }));\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function _map(list, mapper){\r\n");
      out.write("		var new_list = [];\r\n");
      out.write("		for(var i=0;i<list.length;i++){\r\n");
      out.write("			new_list.push(mapper(list[i]));\r\n");
      out.write("		}\r\n");
      out.write("		return new_list;		\r\n");
      out.write("	}\r\n");
      out.write("	//다형성이 굉장히 높고 데이터가 어떻게 생겼는 지에 대해 알 수 없음\r\n");
      out.write("	//관심사가 완전히 분리되는 것\r\n");
      out.write("	\r\n");
      out.write("	var over_30 = _filter(users, function(user) { return user.age >= 30; });\r\n");
      out.write("//	console.log(over_30);\r\n");
      out.write("	\r\n");
      out.write("	var names = _map(over_30, function(user){ return user.name;	});\r\n");
      out.write("	console.log(names);\r\n");
      out.write("	\r\n");
      out.write("	var under_30 = _filter(users, function(user) { return user.age < 30; });\r\n");
      out.write("//	console.log(under_30);\r\n");
      out.write("	\r\n");
      out.write("	var ages = _map(under_30, function(user){\r\n");
      out.write("		return user.age;\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	console.log(ages);\r\n");
      out.write("	\r\n");
      out.write("	console.log(_map([1, 2, 3], function(num) { return num * 2; }));\r\n");
      out.write("	\r\n");
      out.write("/*	함수형 프로그래밍에서는 대입문을 많이 사용하지 않는 경향이 있다.\r\n");
      out.write("	원래 값을 만들어놓고 문장을 내려가면서 변형해나가는 것이 아니라\r\n");
      out.write("	함수를 통과해나가면서 한번에 값을 새롭게 만들어 나가는 식으로 프로그래밍  */\r\n");
      out.write("	\r\n");
      out.write("	console.log(\r\n");
      out.write("		_map(\r\n");
      out.write("			_filter(users, function(user) { return user.age >= 30; }),\r\n");
      out.write("			function(user){ return user.name; }));\r\n");
      out.write("	\r\n");
      out.write("	console.log(\r\n");
      out.write("		_map(\r\n");
      out.write("			_filter(users, function(user){ return user.age < 30; }),\r\n");
      out.write("			function(user) { return user.age; }));\r\n");
      out.write("	\r\n");
      out.write("	function _each(list, iter){\r\n");
      out.write("		for(var i=0; i<list.length; i++){\r\n");
      out.write("			iter(list[i]);\r\n");
      out.write("		}\r\n");
      out.write("		return list;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function _map(list, mapper){\r\n");
      out.write("		var new_list = [];\r\n");
      out.write("		_each(list, function(val){\r\n");
      out.write("			new_list.push(mapper(val));\r\n");
      out.write("		});\r\n");
      out.write("		return new_list;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/*	3. each 만들기  \r\n");
      out.write("		1) _each로 _map, _filter 중복 제거\r\n");
      out.write("		\r\n");
      out.write("		2) 외부 다형성\r\n");
      out.write("		   1. array_like, arguments, document.querySelectorAll\r\n");
      out.write("		      배열이 아니어도 돌릴수 있는 객체들은 모두 돌릴 수 있도록 \r\n");
      out.write("*/\r\n");
      out.write("	console.log(\r\n");
      out.write("		[1, 2, 3].map(function(val){\r\n");
      out.write("			return val * 2;\r\n");
      out.write("		})\r\n");
      out.write("	);\r\n");
      out.write("\r\n");
      out.write("	console.log(\r\n");
      out.write("		[1, 2, 3, 4].map(function(val){\r\n");
      out.write("			return val * 2;\r\n");
      out.write("		})\r\n");
      out.write("	);		\r\n");
      out.write("	\r\n");
      out.write("	console.log(\r\n");
      out.write("		[1, 2, 3, 4].filter(function(val){\r\n");
      out.write("			return val % 2;\r\n");
      out.write("		})		\r\n");
      out.write("	);\r\n");
      out.write("	\r\n");
      out.write("/*	위의 map과 filter는 정확히 말하자면 함수가 아니라 메서드\r\n");
      out.write("	메서드는 객체지향 프로그래밍으로 객체의 상태에 따라 결과가 달라지는 특징을 가짐 \r\n");
      out.write("	메서드의 특징은 해당 클래스에 정의되기 때문에 \r\n");
      out.write("	해당 클래스의 인스턴스에서만 사용 가능  => map이라는 함수는 array가 아니면 사용할 수 없다는 뜻 \r\n");
      out.write("	따라서 객체지향은 다형성을 지원하기에 어려운 부분들이 있음 \r\n");
      out.write("	자바스크립트에는 array가 아닌데 array처럼 여겨지는 객체가 굉장히 많다. (예 jQuery 객체)\r\n");
      out.write("	jQuery객체는 $('div') 이런식으로 어떤 Element를 찾았을 때 리턴된 객체를 말함\r\n");
      out.write("	이 객체는 array가 아니고 arraylike 객체  */\r\n");
      out.write("	\r\n");
      out.write("//	console.log( document.querySelectorAll('*'));\r\n");
      out.write("	//[html, head, meta, title, body, script]\r\n");
      out.write("	//배열 같아 보이지만 배열(array) 아님  = map과 filter 메서드를 사용할 수 없다는 뜻\r\n");
      out.write("	\r\n");
      out.write("/*	console.log(\r\n");
      out.write("		document.querySelectorAll('*').map(function(node) {\r\n");
      out.write("			return node.nodeName;\r\n");
      out.write("		})		\r\n");
      out.write("	);  \r\n");
      out.write("	배열이 아니기 때문에 에러뜸 */\r\n");
      out.write("	\r\n");
      out.write("	console.log(\r\n");
      out.write("		_map(document.querySelectorAll('*'), function(node){\r\n");
      out.write("			return node.nodeName;\r\n");
      out.write("		})		\r\n");
      out.write("	);\r\n");
      out.write("/*	_map은 메서드가 아닌 함수, 배열이 아니어도 동작 \r\n");
      out.write("	우리가 만든 _map은 들어오는 인자가 length가 있고, \r\n");
      out.write("	그것이 숫자여서 0부터 돌았을 때 해당하는 키마다 값이 있으면 사용이 가능   \r\n");
      out.write("	\r\n");
      out.write("	함수가 먼저 나오는 프로그래밍은 데이터가 있기 전부터 함수가 있게 되고\r\n");
      out.write("	데이터가 먼저 나오는 프로그래밍은 데이터가 있어야  메서드가 생긴다. \r\n");
      out.write("	객체지향은 반드시 해당하는 객체가 생겨야 기능을 수행할 수 있기 때문에 평가의 순서가 굉장히  중요하다. \r\n");
      out.write("	\r\n");
      out.write("	함수형은 함수가 혼자 먼저 존재하기 때문에 평가시점이 상대적으로 유연해진다. \r\n");
      out.write("	이것을 이용해 더 높은 조합성을 만들어낼 수 있다. \r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("/*		3) 내부 다형성 \r\n");
      out.write("			1. predi, iter, mapper 내부다형성은 이런 보조함수가 책임진다.\r\n");
      out.write("			해당하는 데이터에 대해서 살펴보는 것 없이 콜백 보조함수에 위임하기 때문에\r\n");
      out.write("			데이터형에 있어서 자유롭고 다형성을 높이는데 유리하다. */\r\n");
      out.write("			\r\n");
      out.write("	_map([1, 2, 3, 4], function(v){\r\n");
      out.write("		return v + 10;\r\n");
      out.write("	});\r\n");
      out.write("/*	함수형 프로그래밍에서는 두번째 함수를 콜백함수라고 하는 경향이 있음\r\n");
      out.write("	콜백함수는 무조건 어떤 일들을 다 수행한 다음에 다시 돌려주는 것을 뜻하는 함수\r\n");
      out.write("	predicate 어떤 조건을 리턴하는 함수\r\n");
      out.write("	iterator 돌면서 반복적으로 실행되는 함수\r\n");
      out.write("	mapper 무언가와 무언가 사이를 매핑하는 함수\r\n");
      out.write("	그냥 콜백함수라고 하기보다는 이렇게 각각의 역할에 맞는 보조함수의 이름으로 따로 불러주는 것이 좋다. \r\n");
      out.write("*/	\r\n");
      out.write("\r\n");
      out.write("/*  3. 커링 \r\n");
      out.write("	      함수와 인자를 다루는 기법 , 함수의 인자를 하나씩 적용해나가다가 필요한 인자가 모두 채워지면 함수 본체를 실행하는 기법 \r\n");
      out.write("	      \r\n");
      out.write("	   1) _curry, _curryr \r\n");
      out.write("	   \r\n");
      out.write("	function _curry(fn){\r\n");
      out.write("		return function(a){\r\n");
      out.write("			return function(b){\r\n");
      out.write("				return fn(a, b);\r\n");
      out.write("		    }\r\n");
      out.write("	    }\r\n");
      out.write("    }*/\r\n");
      out.write("	//위의 코드로는 add(1, 2) 이렇게는 적용되지 않음, f(b){ return fn(a + b) }라고 함수가 리턴돼버림\r\n");
      out.write("	\r\n");
      out.write("	function _curry(fn){\r\n");
      out.write("		return function(a, b){\r\n");
      out.write("			return arguments.length == 2 ? fn(a, b) : function(b) { return fn(a, b); };\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("    //이렇게 수정하면 add(1, 2)도 제대로 실행됨 \r\n");
      out.write("    \r\n");
      out.write("	var add = _curry(function(a, b){\r\n");
      out.write("		return a + b;\r\n");
      out.write("	});\r\n");
      out.write("	//본체함수인 _curry 이하 부분을 갖고 있다가 원하는 시점까지 미뤄뒀다가 최종적으로 평가하는 기법 \r\n");
      out.write("	//계속해서 함수가 함수를 대신 실행하거나, 함수가 함수를 리턴하는 식으로 함수를 조합해나갈 수 있도록 만들어감 \r\n");
      out.write("	//함수에 인자를 하나만 적용하면 함수를 리턴하게 된다\r\n");
      out.write("	\r\n");
      out.write("/*	var add = function(a){\r\n");
      out.write("		return function(b){\r\n");
      out.write("			return fn(a, b);\r\n");
      out.write("		}\r\n");
      out.write("	}; */\r\n");
      out.write("	\r\n");
      out.write("	var add10 = add(10);\r\n");
      out.write("	var add5 = add(5);\r\n");
      out.write("	console.log( add10(5) );\r\n");
      out.write("	console.log( add(5)(3) );\r\n");
      out.write("	console.log( add5(3) );\r\n");
      out.write("	console.log( add(10)(3) );	\r\n");
      out.write("	console.log( add(1, 2) );\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var sub = _curryr(function(a, b){\r\n");
      out.write("		return a - b;\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	console.log( sub(10, 5) ); //10 - 5로 동작\r\n");
      out.write("	var sub10 = sub(10);     \r\n");
      out.write("	console.log( sub10(5) );   //_curry함수를 적용하면 10 - 5로 동작\r\n");
      out.write("	//sub에 _curry가 아닌 _curryr을 적용하면 5 - 10 으로 동작 \r\n");
      out.write("	\r\n");
      out.write("	//오른쪽부터 인자를 적용해나가는 커리 함수\r\n");
      out.write("    function _curryr(fn){\r\n");
      out.write("    	return function(a, b){\r\n");
      out.write("    		return arguments.length == 2 ? fn(a,b) : function(b) { return fn(b, a); };\r\n");
      out.write("    	}\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	/* 2) _get 만들어 좀 더 간단하게 하기 \r\n");
      out.write("	오브젝트에 있는 값을 안전하게 창조하는 함수\r\n");
      out.write("	\r\n");
      out.write("	function _get(obj, key){\r\n");
      out.write("		return obj == null ? undefined : obj[key];\r\n");
      out.write("	} */\r\n");
      out.write("	\r\n");
      out.write("	var _get = _curryr(function(obj, key){\r\n");
      out.write("		return obj == null ? undefined : obj[key];\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	var user1 = users[0];\r\n");
      out.write("	console.log(user1.name);\r\n");
      out.write("	console.log(_get(user1,'name'));\r\n");
      out.write("	console.log(_get('name')(user1));\r\n");
      out.write("	\r\n");
      out.write("	var get_name = _get('name');\r\n");
      out.write("	console.log( get_name(user1) );\r\n");
      out.write("	console.log( get_name(users[3]) );\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	console.log(_map(_filter(users, function(user){return user.age>=30;}), _get('name')));\r\n");
      out.write("	//console.log(users[10].name);\r\n");
      out.write("	//console.log(_get(users[10], 'name'));\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
